ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=bio_local.h

JMK_O_OBJS=b_addr.o b_dump.o b_print.o b_sock.o b_sock2.o bf_buff.o bf_lbuf.o \
  bf_nbio.o bf_null.o bio_cb.o bio_err.o bio_lib.o bio_meth.o bss_acpt.o \
  bss_bio.o bss_conn.o bss_dgram.o bss_fd.o bss_file.o bss_log.o bss_mem.o \
  bss_null.o bss_sock.o

$(call JMKE_INCLUDE_RULES)

