ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS+=config internal
JMK_EXPORT_HEADERS_DIR=freetype
JMK_EXPORT_HEADERS+=freetype.h ftadvanc.h ftbbox.h ftbdf.h ftbitmap.h \
  ftcache.h ftchapters.h ftcid.h fterrdef.h fterrors.h ftgasp.h ftglyph.h \
  ftgxval.h ftgzip.h ftimage.h ftincrem.h ftlcdfil.h ftlist.h ftlzw.h ftmac.h \
  ftmm.h ftmodapi.h ftmoderr.h ftotval.h ftoutln.h ftpfr.h ftrender.h \
  ftsizes.h ftsnames.h ftstroke.h ftsynth.h ftsystem.h fttrigon.h fttypes.h \
  ftwinfnt.h ftxf86.h t1tables.h ttnameid.h tttables.h tttags.h ttunpat.h

$(call JMKE_INCLUDE_RULES)
