ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=poly1305_local.h

JMK_O_OBJS=poly1305.o poly1305_ameth.o poly1305_pmeth.o

$(call JMKE_INCLUDE_RULES)

