ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=x509_local.h

JMK_O_OBJS=by_dir.o by_file.o t_crl.o t_req.o t_x509.o x509_att.o x509_cmp.o \
  x509_d2.o x509_def.o x509_err.o x509_ext.o x509_lu.o x509_meth.o x509_obj.o \
  x509_r2x.o x509_req.o x509_set.o x509_trs.o x509_txt.o x509_v3.o x509_vfy.o \
  x509_vpm.o x509cset.o x509name.o x509rset.o x509spki.o x509type.o x_all.o \
  x_attrib.o x_crl.o x_exten.o x_name.o x_pubkey.o x_req.o x_x509.o x_x509a.o

$(call JMKE_INCLUDE_RULES)
