ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS=arch

JMK_INTERNAL_HEADERS=async_local.h

JMK_O_OBJS=async.o async_err.o async_wait.o

$(call JMKE_INCLUDE_RULES)

