JMK_ROOT=../../../..
include $(JMK_ROOT)/envir.mak

JMK_EXPORT_HEADERS_DIR=libxml
JMK_EXPORT_HEADERS+=DOCBparser.h HTMLparser.h HTMLtree.h SAX.h SAX2.h c14n.h \
  catalog.h chvalid.h debugXML.h dict.h encoding.h entities.h globals.h \
  hash.h list.h nanoftp.h nanohttp.h parser.h parserInternals.h pattern.h \
  relaxng.h schemasInternals.h schematron.h threads.h tree.h uri.h valid.h \
  xinclude.h xlink.h xmlIO.h xmlautomata.h xmlerror.h xmlexports.h xmlmemory.h \
  xmlmodule.h xmlreader.h xmlregexp.h xmlsave.h xmlschemas.h xmlschemastypes.h \
  xmlstring.h xmlunicode.h xmlversion.h xmlwriter.h xpath.h xpathInternals.h \
  xpointer.h

include $(JMKE_MK)

