ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=ui_local.h

JMK_O_OBJS=ui_err.o ui_lib.o ui_null.o ui_openssl.o ui_util.o

$(call JMKE_INCLUDE_RULES)
