ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=spr.h des_local.h ncbc_enc.c

JMK_O_OBJS=cbc_cksm.o cbc_enc.o cfb64ede.o cfb64enc.o cfb_enc.o des_enc.o \
  ecb3_enc.o ecb_enc.o fcrypt.o fcrypt_b.o ofb64ede.o ofb64enc.o ofb_enc.o \
  pcbc_enc.o qud_cksm.o rand_key.o set_key.o str2key.o xcbc_enc.o

$(call JMKE_INCLUDE_RULES)
