ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../..
  include $(JMK_ROOT)/jmk/env_root.mak
endif
include $(JMK_ROOT)/pkg/voip/asterisk/db1-ast/common.mak

JMK_O_TARGET=db_target.o
JMK_O_OBJS=db.o

$(call JMKE_INCLUDE_RULES)
