SMBDIR=..
include $(SMBDIR)/envir.mak

JMK_A_TARGET=libtdb.a
JMK_O_OBJS=common/tdb.o common/open.o common/traverse.o common/lock.o common/io.o \
       common/transaction.o common/freelist.o common/error.o

include $(SMBMK)

