ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=dsa_local.h

JMK_O_OBJS=dsa_ameth.o dsa_asn1.o dsa_depr.o dsa_err.o dsa_gen.o dsa_key.o \
  dsa_lib.o dsa_meth.o dsa_ossl.o dsa_pmeth.o dsa_prn.o dsa_sign.o dsa_vrf.o

$(call JMKE_INCLUDE_RULES)

