ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=cms_local.h

JMK_O_OBJS=cms_asn1.o cms_att.o cms_cd.o cms_dd.o cms_enc.o cms_env.o \
  cms_err.o cms_ess.o cms_io.o cms_kari.o cms_lib.o cms_pwri.o cms_sd.o \
  cms_smime.o

$(call JMKE_INCLUDE_RULES)

