ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=ct_local.h

JMK_O_OBJS=ct_b64.o ct_err.o ct_log.o ct_oct.o ct_policy.o ct_prn.o ct_sct.o \
  ct_sct_ctx.o ct_vfy.o ct_x509v3.o

$(call JMKE_INCLUDE_RULES)

