ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=cast_local.h cast_s.h

JMK_O_OBJS=c_cfb64.o c_ecb.o c_enc.o c_ofb64.o c_skey.o

$(call JMKE_INCLUDE_RULES)

