SMBDIR=..
include $(SMBDIR)/envir.mak

JMK_A_TARGET=libregistry.a
JMK_O_OBJS=reg_objects.o reg_frontend.o reg_cachehook.o reg_printing.o reg_db.o \
       reg_util.o reg_dynamic.o reg_perfcount.o reg_shares.o reg_eventlog.o \
       regfio.o

include $(SMBMK)
