ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=cmll_local.h

JMK_O_OBJS=cmll_cfb.o cmll_ctr.o cmll_ecb.o cmll_misc.o cmll_ofb.o

$(call JMKE_INCLUDE_RULES)

