ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS+=sigc++

JMK_EXPORT_HEADERS=sigc++config.h 
JMK_INTERNAL_HEADERS=config.h

$(call JMKE_INCLUDE_RULES)
