ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS+=err.h sockets.h o_dir.h o_str.h conf.h thread_once.h \
  refcount.h cryptlib.h comp.h numbers.h sslconf.h dsoerr.h tsan_assist.h \
  constant_time.h dane.h dso.h bio.h nelem.h

$(call JMKE_INCLUDE_RULES)
