ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=rsa_local.h

JMK_O_OBJS=rsa_ameth.o rsa_asn1.o rsa_chk.o rsa_crpt.o rsa_depr.o rsa_err.o \
  rsa_gen.o rsa_lib.o rsa_meth.o rsa_mp.o rsa_none.o rsa_oaep.o rsa_ossl.o \
  rsa_pk1.o rsa_pmeth.o rsa_prn.o rsa_pss.o rsa_saos.o rsa_sign.o rsa_ssl.o \
  rsa_x931.o rsa_x931g.o

$(call JMKE_INCLUDE_RULES)
