ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_RAMDISK_ETC_FILES+=iproute2/ematch_map iproute2/group iproute2/rt_dsfield \
  iproute2/rt_protos iproute2/rt_realms iproute2/rt_scopes iproute2/rt_tables

$(call JMKE_INCLUDE_RULES)
