ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=ocsp_local.h

JMK_O_OBJS=ocsp_asn.o ocsp_cl.o ocsp_err.o ocsp_ext.o ocsp_ht.o ocsp_lib.o \
  ocsp_prn.o ocsp_srv.o ocsp_vfy.o v3_ocsp.o

$(call JMKE_INCLUDE_RULES)

