ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=blake2_local.h blake2_impl.h

JMK_O_OBJS=blake2b.o blake2s.o m_blake2b.o m_blake2s.o

$(call JMKE_INCLUDE_RULES)

