ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=ts_local.h

JMK_O_OBJS=ts_asn1.o ts_conf.o ts_err.o ts_lib.o ts_req_print.o ts_req_utils.o \
  ts_rsp_print.o ts_rsp_sign.o ts_rsp_utils.o ts_rsp_verify.o ts_verify_ctx.o

$(call JMKE_INCLUDE_RULES)
