ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=evp_local.h

JMK_O_OBJS=bio_b64.o bio_enc.o bio_md.o bio_ok.o c_allc.o c_alld.o cmeth_lib.o \
  digest.o e_aes.o e_aes_cbc_hmac_sha1.o e_aes_cbc_hmac_sha256.o e_aria.o \
  e_bf.o e_cast.o e_des.o e_des3.o e_idea.o e_null.o e_old.o e_rc2.o e_rc4.o \
  e_rc4_hmac_md5.o e_rc5.o e_seed.o e_sm4.o e_xcbc_d.o encode.o evp_cnf.o \
  evp_enc.o evp_err.o evp_key.o evp_lib.o evp_pbe.o evp_pkey.o m_md2.o m_md4.o \
  m_md5.o m_md5_sha1.o m_mdc2.o m_null.o m_ripemd.o m_sha1.o m_sha3.o \
  m_sigver.o m_wp.o names.o p5_crpt.o p5_crpt2.o p_dec.o p_enc.o p_lib.o \
  p_open.o p_seal.o p_sign.o p_verify.o	pbe_scrypt.o pmeth_fn.o pmeth_gn.o \
  pmeth_lib.o

$(call JMKE_INCLUDE_RULES)
