ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=dso_local.h

JMK_O_OBJS=dso_dl.o dso_dlfcn.o dso_err.o dso_lib.o dso_openssl.o dso_vms.o \
  dso_win32.o

$(call JMKE_INCLUDE_RULES)

