SMBDIR=..
include $(SMBDIR)/envir.mak

JMK_A_TARGET=librpc.a
JMK_O_OBJS=ndr/ndr_basic.o ndr/ndr.o  ndr/ndr_misc.o ndr/ndr_string.o \
  gen_ndr/srv_wkssvc.o gen_ndr/ndr_wkssvc.o gen_ndr/ndr_notify.o

include $(SMBMK)
