ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=siphash_local.h

JMK_O_OBJS=siphash.o siphash_ameth.o siphash_pmeth.o

$(call JMKE_INCLUDE_RULES)

