ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../..
  include $(JMK_ROOT)/jmk/env_root.mak
endif
include $(JMK_ROOT)/pkg/voip/asterisk/db1-ast/common.mak

JMK_O_TARGET=recno_target.o
JMK_O_OBJS=rec_close.o rec_delete.o rec_get.o rec_open.o rec_put.o rec_search.o \
  rec_seq.o rec_utils.o

$(call JMKE_INCLUDE_RULES)
