ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS+=ec.h err.h md32_common.h ctype.h lhash.h asn1.h store.h \
  rand.h cryptlib.h chacha.h bn.h sm4.h siphash.h objects.h sm2.h engine.h \
  sha.h bn_srp.h bn_dh.h sm3.h async.h x509.h poly1305.h sm2err.h aria.h evp.h

$(call JMKE_INCLUDE_RULES)
