ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=rand_local.h

JMK_O_OBJS=drbg_ctr.o drbg_lib.o rand_egd.o rand_err.o rand_lib.o rand_unix.o \
  randfile.o

$(call JMKE_INCLUDE_RULES)
