ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS+=lambda

JMK_EXPORT_HEADERS_DIR=sigc++/adaptors
JMK_EXPORT_HEADERS=adaptors.h adaptor_trait.h bind.h bind_return.h \
  bound_argument.h compose.h deduce_result_type.h exception_catch.h hide.h \
  retype.h retype_return.h

$(call JMKE_INCLUDE_RULES)
