#
# You may have to ajust to call the right compiler, or other oprions
# for compiling and linking
#

JMK_CFLAGS=`xml2-config --cflags`
LIBS=`xml2-config --libs`
THREADLIB= -lpthread
EXEEXT=

all: runtest$(EXEEXT) runsuite$(EXEEXT) testapi$(EXEEXT)

clean:
	$(RM) runtest$(EXEEXT) runsuite$(EXEEXT) testapi$(EXEEXT)

check: do_runtest do_runsuite do_testapi

runtest$(EXEEXT): runtest.c
	$(CC) -o runtest$(EXEEXT) $(JMK_CFLAGS) runtest.c $(LIBS) $(THREADLIB)

do_runtest: runtest$(EXEEXT)
	./runtest

runsuite$(EXEEXT): runsuite.c
	$(CC) -o runsuite$(EXEEXT) $(JMK_CFLAGS) runsuite.c $(LIBS)

do_runsuite: runsuite$(EXEEXT)
	./runsuite

testapi$(EXEEXT): testapi.c
	$(CC) -o testapi$(EXEEXT) $(JMK_CFLAGS) testapi.c $(LIBS)

do_testapi: testapi$(EXEEXT)
	./testapi

