ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=comp_local.h

JMK_O_OBJS=c_zlib.o comp_err.o comp/comp_lib.o

$(call JMKE_INCLUDE_RULES)

