ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS+=linux/tc_act/tc_gact.h linux/netlink.h \
  linux/pkt_cls.h linux/pkt_sched.h linux/rtnetlink.h linux/tcp.h \
  linux/tcp_diag.h linux/xfrm.h SNAPSHOT.h libnetlink.h ll_map.h rt_names.h \
  rtm_map.h utils.h linux/pkt_sched.h linux/pkt_cls.h

$(call JMKE_INCLUDE_RULES)
