ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=openssl
JMK_EXPORT_HEADERS+=ec.h err.h objectserr.h ecerr.h x509v3.h ssl2.h \
  x509v3err.h txt_db.h ui.h des.h x509err.h symhacks.h pkcs12err.h dherr.h \
  lhash.h kdferr.h md2.h rsa.h ossl_typ.h crypto.h conf.h e_os2.h stack.h \
  dsa.h evperr.h srp.h md5.h dh.h randerr.h rsaerr.h asn1.h ripemd.h store.h \
  ct.h ocsp.h rand.h kdf.h asyncerr.h pemerr.h uierr.h comp.h camellia.h \
  storeerr.h ocsperr.h x509_vfy.h tls1.h srtp.h comperr.h blowfish.h bn.h \
  pkcs12.h ecdh.h safestack.h pkcs7err.h objects.h asn1_mac.h pem.h opensslv.h \
  conferr.h engine.h asn1err.h ts.h opensslconf.h sha.h dtls1.h cmserr.h \
  whrlpool.h pem2.h cast.h modes.h ssl3.h cryptoerr.h rc2.h ssl.h rc5.h \
  asn1t.h conf_api.h ebcdic.h rand_drbg.h aes.h tserr.h rc4.h async.h ecdsa.h \
  buffer.h hmac.h x509.h engineerr.h seed.h cterr.h cmac.h buffererr.h pkcs7.h \
  md4.h bnerr.h bioerr.h sslerr.h bio.h mdc2.h cms.h dsaerr.h idea.h evp.h

$(call JMKE_INCLUDE_RULES)
