ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=asn1_item_list.h asn1_local.h standard_methods.h \
  charmap.h tbl_standard.h

JMK_O_OBJS=a_bitstr.o a_d2i_fp.o a_digest.o a_dup.o a_gentm.o a_i2d_fp.o \
  a_int.o a_mbstr.o a_object.o a_octet.o a_print.o a_sign.o a_strex.o \
  a_strnid.o a_time.o a_type.o a_utctm.o a_utf8.o a_verify.o ameth_lib.o \
  asn1_err.o asn1_gen.o asn1_item_list.o asn1_lib.o asn1_par.o asn_mime.o \
  asn_moid.o asn_mstbl.o asn_pack.o bio_asn1.o bio_ndef.o d2i_pr.o d2i_pu.o \
  evp_asn1.o f_int.o f_string.o i2d_pr.o i2d_pu.o n_pkey.o nsseq.o p5_pbe.o \
  p5_pbev2.o p5_scrypt.o p8_pkey.o t_bitst.o t_pkey.o t_spki.o tasn_dec.o \
  tasn_enc.o tasn_fre.o tasn_new.o tasn_prn.o tasn_scn.o tasn_typ.o tasn_utl.o \
  x_algor.o x_bignum.o x_info.o x_int64.o x_long.o x_pkey.o x_sig.o x_spki.o \
  x_val.o

$(call JMKE_INCLUDE_RULES)

