ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=async_null.h async_posix.h async_win.h

JMK_O_OBJS=async_null.o async_posix.o async_win.o

$(call JMKE_INCLUDE_RULES)
