ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../..
  include $(JMK_ROOT)/jmk/env_root.mak
endif
include $(JMK_ROOT)/pkg/voip/asterisk/common.mak

JMK_A_TARGET=libtime.a
JMK_O_OBJS_libtime.a=localtime.o

$(call JMKE_INCLUDE_RULES)
