ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=conf_def.h conf_local.h

JMK_O_OBJS=conf_api.o conf_def.o conf_err.o conf_lib.o conf_mall.o conf_mod.o \
  conf_sap.o conf_ssl.o

$(call JMKE_INCLUDE_RULES)

