ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=aes_local.h

JMK_O_OBJS=aes_cbc.o aes_cfb.o aes_core.o aes_ecb.o aes_ige.o aes_misc.o \
  aes_ofb.o aes_wrap.o 

$(call JMKE_INCLUDE_RULES)

