ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_O_TARGET=minizip.o
JMK_LOCAL_O_TARGET=local_$(JMK_O_TARGET)
JMK_O_OBJS=zip.o

JMK_EXPORT_HEADERS_DIR=minizip
JMK_EXPORT_HEADERS+=zip.h

$(call JMKE_INCLUDE_RULES)
