JMK_ROOT=../../../../
include $(JMK_ROOT)/envir.mak

JMK_EXPORT_HEADERS_DIR=ntfs-3g
JMK_EXPORT_HEADERS+=acls.h bitmap.h collate.h debug.h dir.h endians.h ioctl.h \
  logfile.h misc.h object_id.h realpath.h security.h unistr.h attrib.h \
  bootsect.h compat.h device.h ea.h index.h layout.h logging.h mst.h param.h \
  reparse.h support.h volume.h attrlist.h cache.h compress.h device_io.h efs.h \
  inode.h lcnalloc.h mft.h ntfstime.h plugin.h runlist.h types.h xattrs.h

include $(JMKE_MK)
