ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_INTERNAL_HEADERS=modes_local.h

JMK_O_OBJS=cbc128.o ccm128.o cfb128.o ctr128.o cts128.o gcm128.o ocb128.o \
  ofb128.o wrap128.o xts128.o

$(call JMKE_INCLUDE_RULES)
