ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=sha1dgst.c__c/sha1dgst.c
JMK_INTERNAL_HEADERS=sha_local.h

JMK_O_OBJS=keccak1600.o sha1_one.o sha1dgst.o sha256.o sha512.o

$(call JMKE_INCLUDE_RULES)
