SMBDIR=..
include $(SMBDIR)/envir.mak

JMK_A_TARGET=librpc_parse.a
JMK_O_OBJS=parse_prs.o parse_sec.o parse_misc.o parse_lsa.o parse_net.o \
  parse_reg.o parse_rpc.o parse_samr.o parse_srv.o parse_ds.o \
  parse_spoolss.o parse_dfs.o parse_echo.o parse_shutdown.o parse_buffer.o \
  parse_eventlog.o parse_ntsvcs.o parse_svcctl.o

include $(SMBMK)
