ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS+=svbdf.h svcid.h svgldict.h svgxval.h svkern.h svmm.h \
  svotval.h svpfr.h svpostnm.h svpscmap.h svpsinfo.h svsfnt.h svttcmap.h \
  svtteng.h svttglyf.h svwinfnt.h svxf86nm.h

$(call JMKE_INCLUDE_RULES)
