ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS=dh_local.h

JMK_O_OBJS=dh_ameth.o dh_asn1.o dh_check.o dh_depr.o dh_err.o dh_gen.o \
  dh_kdf.o dh_key.o dh_lib.o dh_meth.o dh_pmeth.o dh_prn.o dh_rfc5114.o \
  dh_rfc7919.o

$(call JMKE_INCLUDE_RULES)

