ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_WARN2ERR=n

JMK_O_OBJS=pem_all.o pem_err.o pem_info.o pem_lib.o pem_oth.o pem_pk8.o \
  pem_pkey.o pem_sign.o pem_x509.o pem_xaux.o pvkfmt.o

$(call JMKE_INCLUDE_RULES)

