ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_EXPORT_HEADERS_DIR=freetype/config
JMK_EXPORT_HEADERS+=ftconfig.h ftheader.h ftmodule.h ftoption.h ftstdlib.h

$(call JMKE_INCLUDE_RULES)
