ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=store_local.h

JMK_O_OBJS=loader_file.o store_err.o store_init.o store_lib.o store_register.o \
  store_strings.o

$(call JMKE_INCLUDE_RULES)
