ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=seed_local.h

JMK_O_OBJS=seed.o seed_ecb.o seed_cbc.o seed_cfb.o seed_ofb.o

$(call JMKE_INCLUDE_RULES)
