ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=bf_local.h bf_pi.h

JMK_O_OBJS=bf_cfb64.o bf_ecb.o bf_enc.o bf_ofb64.o bf_skey.o

$(call JMKE_INCLUDE_RULES)

