SMBDIR=..
include $(SMBDIR)/envir.mak

JMK_A_TARGET=librpc_server.a
JMK_O_OBJS=srv_dfs_nt.o srv_dfs.o srv_lsa_hnd.o srv_lsa_nt.o srv_lsa.o \
  srv_netlog_nt.o srv_netlog.o srv_pipe_hnd.o srv_pipe.o srv_reg_nt.o \
  srv_reg.o srv_samr_nt.o srv_samr_util.o srv_samr.o srv_spoolss_nt.o \
  srv_spoolss.o srv_srvsvc_nt.o srv_srvsvc.o srv_util.o srv_wkssvc_nt.o \
  srv_lsa_ds.o srv_lsa_ds_nt.o srv_echo.o srv_echo_nt.o \
  srv_svcctl_nt.o srv_svcctl.o srv_eventlog.o srv_ntsvcs.o srv_eventlog_nt.o \
  srv_ntsvcs_nt.o srv_eventlog_lib.o srv_wkssvc_nt.o

include $(SMBMK)
