ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_SUBDIRS+=services

JMK_INTERNAL_HEADERS+=autohint.h ftcalc.h ftdebug.h ftdriver.h ftgloadr.h \
  ftmemory.h ftobjs.h ftpic.h ftrfork.h ftserv.h ftstream.h fttrace.h \
  ftvalid.h internal.h pcftypes.h psaux.h pshints.h sfnt.h t1types.h tttypes.h

$(call JMKE_INCLUDE_RULES)
