ifndef JMKE_ENV_INCLUDED
  JMK_ROOT=../../../../
  include $(JMK_ROOT)/jmk/env_root.mak
endif

JMK_INTERNAL_HEADERS=pcy_local.h ext_dat.h v3_admis.h standard_exts.h

JMK_O_OBJS=pcy_cache.o pcy_data.o pcy_lib.o pcy_map.o pcy_node.o pcy_tree.o \
  v3_addr.o v3_admis.o v3_akey.o v3_akeya.o v3_alt.o v3_asid.o v3_bcons.o \
  v3_bitst.o v3_conf.o v3_cpols.o v3_crld.o v3_enum.o v3_extku.o v3_genn.o \
  v3_ia5.o v3_info.o v3_int.o v3_lib.o v3_ncons.o v3_pci.o v3_pcia.o \
  v3_pcons.o v3_pku.o v3_pmaps.o v3_prn.o v3_purp.o v3_skey.o v3_sxnet.o \
  v3_tlsf.o v3_utl.o v3err.o

$(call JMKE_INCLUDE_RULES)
